"use client";
import {useEffect,useRef,useState} from 'react';
import {gsap} from 'gsap';
import {ScrollTrigger} from 'gsap/ScrollTrigger';
import * as THREE from 'three';
import {ArrowUpRight,ArrowDown,Pause,Play,MoveUpRight} from 'lucide-react';
import {ImageStreamHero} from '@/components/ui/image-stream-hero';
const images=[{src:'/images/01.jpg',alt:'Surreal sunset and sea portrait'},{src:'/images/02.jpg',alt:'City skyline portrait'},{src:'/images/03.jpg',alt:'Portrait in motion'},{src:'/images/04.jpg',alt:'Colour in motion'},{src:'/images/05.jpg',alt:'Bird and human gesture'}];
function softwareSculpture(el:HTMLDivElement,pause:{current:boolean}){
 const canvas=document.createElement('canvas');el.appendChild(canvas);const ctx=canvas.getContext('2d');if(!ctx)return()=>canvas.remove();
 const geom=new THREE.TorusKnotGeometry(1.23,.39,96,16,2,3),pos=geom.attributes.position,normal=geom.attributes.normal,idx=geom.index!;const camera=new THREE.PerspectiveCamera(40,1,.1,100);camera.position.z=7;camera.updateMatrixWorld();const matrix=new THREE.Matrix4(),rot=new THREE.Euler(.25,0,.2);let frame=0,prev=0,w=1,h=1,x=.25;const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;
 const resize=()=>{w=el.clientWidth;h=el.clientHeight;canvas.width=w;canvas.height=h;camera.aspect=w/h;camera.updateProjectionMatrix()};const ro=new ResizeObserver(resize);ro.observe(el);resize();
 const move=(e:PointerEvent)=>{x=(e.clientY-el.getBoundingClientRect().top)/h-.5};el.addEventListener('pointermove',move);
 const light=new THREE.Vector3(-.5,.8,1).normalize();const render=(time:number)=>{frame=requestAnimationFrame(render);if(time-prev<40||document.hidden)return;prev=time;if(!pause.current&&!reduce){rot.y+=.008;rot.x+=(x-rot.x)*.03;}matrix.makeRotationFromEuler(rot);ctx.clearRect(0,0,w,h);const pts:THREE.Vector3[]=[],norms:THREE.Vector3[]=[];for(let i=0;i<pos.count;i++){pts.push(new THREE.Vector3().fromBufferAttribute(pos,i).applyMatrix4(matrix));norms.push(new THREE.Vector3().fromBufferAttribute(normal,i).transformDirection(matrix));}const faces=[];for(let i=0;i<idx.count;i+=3){const a=idx.getX(i),b=idx.getX(i+1),c=idx.getX(i+2);faces.push({a,b,c,z:(pts[a].z+pts[b].z+pts[c].z)/3})}faces.sort((a,b)=>a.z-b.z);const projected=pts.map(p=>p.clone().project(camera));for(const f of faces){const n=norms[f.a].clone().add(norms[f.b]).add(norms[f.c]).normalize();const d=Math.max(0,n.dot(light));const spec=Math.pow(Math.max(0,n.dot(new THREE.Vector3(-.3,.5,1).normalize())),32);const l=20+d*49+spec*28;ctx.fillStyle=`hsl(76,${55-spec*40}%,${l}%)`;ctx.beginPath();[f.a,f.b,f.c].forEach((i,k)=>{const p=projected[i],xx=(p.x*.5+.5)*w,yy=(-p.y*.5+.5)*h;k?ctx.lineTo(xx,yy):ctx.moveTo(xx,yy)});ctx.closePath();ctx.fill();} };render(0);return()=>{cancelAnimationFrame(frame);ro.disconnect();geom.dispose();el.removeEventListener('pointermove',move);canvas.remove()}
}
function Sculpture({paused}:{paused:boolean}){
 const host=useRef<HTMLDivElement>(null);const pause=useRef(paused);useEffect(()=>{pause.current=paused},[paused]);
 useEffect(()=>{const el=host.current;if(!el)return;let renderer:THREE.WebGLRenderer;try{renderer=new THREE.WebGLRenderer({alpha:true,antialias:true});}catch{return softwareSculpture(el,pause);}
 renderer.setPixelRatio(Math.min(devicePixelRatio,1.75));el.appendChild(renderer.domElement);const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(40,1,.1,100);camera.position.z=7;
 const geo=new THREE.TorusKnotGeometry(1.23,.39,192,32,2,3);const mat=new THREE.MeshPhysicalMaterial({color:0xd4ff51,metalness:.83,roughness:.21,clearcoat:1});const mesh=new THREE.Mesh(geo,mat);scene.add(mesh);scene.add(new THREE.HemisphereLight(0xffffff,0x384625,3));const light=new THREE.PointLight(0xffffff,75);light.position.set(3,4,4);scene.add(light);const rim=new THREE.PointLight(0x97b3ff,45);rim.position.set(-4,-1,2);scene.add(rim);
 const ring=new THREE.Mesh(new THREE.TorusGeometry(2.25,.006,6,160),new THREE.MeshBasicMaterial({color:0x626953}));ring.rotation.x=1.1;scene.add(ring);let x=0,y=0,frame=0,visible=true;const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;
 const resize=()=>{const w=el.clientWidth,h=el.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix()};const ro=new ResizeObserver(resize);ro.observe(el);const io=new IntersectionObserver(([e])=>visible=e.isIntersecting);io.observe(el);const move=(e:PointerEvent)=>{const r=el.getBoundingClientRect();x=((e.clientX-r.left)/r.width-.5)*1.2;y=((e.clientY-r.top)/r.height-.5)*.8};el.addEventListener('pointermove',move);
 const render=()=>{frame=requestAnimationFrame(render);if(!visible||document.hidden)return;if(!pause.current&&!reduce){mesh.rotation.y+=.004;mesh.rotation.z+=.0015;mesh.rotation.x+=(y-mesh.rotation.x)*.025;ring.rotation.z+=.002;}mesh.position.x+=(x*.2-mesh.position.x)*.03;renderer.render(scene,camera)};resize();render();return()=>{cancelAnimationFrame(frame);ro.disconnect();io.disconnect();el.removeEventListener('pointermove',move);geo.dispose();mat.dispose();ring.geometry.dispose();(ring.material as THREE.Material).dispose();renderer.dispose();renderer.domElement.remove()}
 },[]);return <div className="sculpture" ref={host} aria-label="Interactive rotating lime metallic sculpture" role="img"/>;
}
export default function Home(){const root=useRef<HTMLDivElement>(null);const [paused,setPaused]=useState(false);const [theme,setTheme]=useState(0);
 useEffect(()=>{gsap.registerPlugin(ScrollTrigger);const mm=gsap.matchMedia();mm.add('(prefers-reduced-motion: no-preference)',()=>{const ctx=gsap.context(()=>{gsap.from('.hero-title span',{y:100,opacity:0,duration:1.4,stagger:.13,ease:'power4.out'});gsap.from('.hero-kicker,.hero-bottom',{opacity:0,y:20,duration:1,delay:.7});gsap.utils.toArray<HTMLElement>('.reveal').forEach(el=>gsap.from(el,{y:65,opacity:0,duration:1.1,ease:'power3.out',scrollTrigger:{trigger:el,start:'top 90%'}}));gsap.to('.hero-title',{y:-70,opacity:.15,scrollTrigger:{trigger:'.hero',start:'top top',end:'bottom top',scrub:1}});gsap.to('.manifesto-word',{xPercent:-12,scrollTrigger:{trigger:'.manifesto',start:'top bottom',end:'bottom top',scrub:1}});},root);return()=>ctx.revert()});return()=>mm.revert()},[]);
 const stream=theme===0?images:theme===1?[images[0],images[1],images[4]]:[images[2],images[3],images[1]];
 return <div ref={root} className={paused?'site motion-paused':'site'}>
 <header className="nav"><a className="brand" href="#" aria-label="FRAME home">fr<span className="brand-a">a</span>me<span className="brand-dot">®</span></a><nav><a href="#explore">The collection <span>05</span></a><a href="#dimension">Playground</a></nav><a className="nav-cta" href="#explore">Step inside <ArrowUpRight size={17}/></a></header>
 <section className="hero" aria-labelledby="hero-title"><ImageStreamHero images={stream} cards={10} speed={22} axis={57} path={{exitHeight:43,railExit:46,cardRadius:.25}} className="corridor"><div className="hero-top"><p className="hero-kicker"><span className="tiny-cross">✳</span> AN INDEPENDENT EXPLORATION OF IMAGE & MOTION</p><h1 id="hero-title" className="hero-title"><span>Beyond the</span><span>ordinary<span className="title-star">*</span></span></h1></div><div className="center-label"><span>IMAGINATION, IN EVERY DIRECTION.</span></div><div className="hero-bottom"><p>Different perspectives.<br/>Unexpected possibilities.</p><a href="#explore" className="explore-button">Explore the collection <ArrowDown size={17}/></a><div className="edition">DIGITAL EXHIBITION<br/><span>VOL. 001 — 2026</span></div></div></ImageStreamHero><div className="hero-controls"><span>CURATE YOUR VIEW</span><div className="view-options">{['All frames','Dream state','Full colour'].map((t,i)=><button aria-pressed={theme===i} key={t} onClick={()=>setTheme(i)} className={theme===i?'selected':''}>{t}</button>)}</div><button className="pause" onClick={()=>setPaused(!paused)} aria-label={paused?'Play animation':'Pause animation'}>{paused?<Play size={14}/>:<Pause size={14}/>}<span>{paused?'Play motion':'Pause motion'}</span></button></div></section>
 <section id="explore" className="collection"><div className="section-head reveal"><p className="eyebrow">01 / THE COLLECTION</p><h2>A different way<br/>of seeing things.</h2><p>A little surreal. A little unexpected.<br/>A world that moves beyond the frame.</p></div><div className="art-grid">{images.map((im,i)=><figure className={'art reveal art-'+i} key={im.src}><div className="art-image"><img src={im.src} alt={im.alt} loading="lazy"/><span className="art-index">0{i+1}</span><span className="art-hover">A NEW PERSPECTIVE <MoveUpRight size={25}/></span></div><figcaption><div><h3>{['Somewhere, within','City of the mind','Afterimage','Colour in motion','Let it fly'][i]}</h3><p>{['Dreamscapes','Double exposure','Motion studies','Chromatic experiments','Surreal perspectives'][i]}</p></div><span>2026</span></figcaption></figure>)}</div></section>
 <section id="dimension" className="dimension"><div className="dimension-copy reveal"><p className="eyebrow">02 / ANOTHER DIMENSION</p><h2>Nothing<br/>stands <em>still.</em></h2><p>Follow your curiosity.<br/>Move your cursor and shift your perspective.</p><span className="dimension-tag">AN EXPERIMENT IN ENDLESS FORM</span></div><Sculpture paused={paused}/><span className="object-meta">OBJECT 001<br/>INFINITE LOOP</span><span className="object-axis">X · Y · Z</span></section>
 <section className="manifesto"><p className="eyebrow reveal">THE ONLY LIMIT IS THE EDGE OF YOUR IMAGINATION.</p><div className="manifesto-word">STAY CURIOUS<span>✳</span></div><a className="back-top" href="#">One more trip? <ArrowUpRight size={22}/></a></section><footer><a className="brand" href="#">frame®</a><p>Made for the curious.</p><span>© FRAME 2026</span></footer>
 </div>
}
